version: 3.3
services:
    nginx:
        image:nginx
        volumes:
            - /root/cert:/root/cert:ro
            - /root/nginx/proxy.conf:/etc/nginx/conf.d/default.conf
        ports:
            - 80:80
            - 443:443
        networks: 
          - viz_deltares_net
          - vre_net
        container_name: proxy_nginx

networks:
    viz_deltares_net:
        external: true
            name: viz_deltares
    vre_net:
        external: true
            name: vre

